spring.application.name=poker-server

# Database
spring.datasource.url=jdbc:postgresql://db:5432/poker_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Redis connection
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=6379

# Logging
logging.level.org.springframework.data.redis=INFO