spring.application.name=poker-server

# Database connection
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/poker_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password} 

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true